### ISSUE TITLE
/api/teaching still returning null, when i have one 

### ISSUE THREAD

**Issue by Arukenofu** [Rehart-Kcalb/EduNexus-Monolith#7] opened 2024-06-07 10:24 UTC
![изображение](https://github.com/Rehart-Kcalb/EduNexus-Monolith/assets/126886598/f9591c1c-db54-4478-9ddc-b8deaf016038)

**Comment by Rehart-Kcalb** [comment] 2024-06-07 10:31
Duplicate of previous issue

**Closed** 2024-06-07 23:57 UTC
